spring:
  application:
    name: stock-service
  cloud:
    consul:
      host: localhost
      port: 8501
      discovery:
        serviceName: stock-service
        enabled: true
        instanceId: ${spring.application.name}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        healthCheckTimeout: 10s
        preferIpAddress: true
      config:
        enabled: false

server:
  port: 8900

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
