services:
  stock-service:
    build:
      context: ./stock-service
    container_name: stock-service
    ports:
      - "8900:8900"
    restart: unless-stopped
    networks:
      - services-net

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8902:8902"
    environment:
      STOCK_SERVICE_URL: http://stock-service:8900
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/sa_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - stock-service
    restart: unless-stopped
    networks:
      - services-net

networks:
  services-net:
    driver: bridge