services:
  stock-service:
    build:
      context: ./stock-service
    container_name: stock-service
    ports:
      - "8900:8900"
    restart: unless-stopped
    networks:
      - services-net

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8902:8902"
    environment:
      STOCK_SERVICE_URL: http://stock-service:8900
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/sa_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - stock-service
    restart: unless-stopped
    networks:
      - services-net

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    networks:
      - services-net
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka=INFO,kafka.network=INFO,kafka.cluster=INFO,org.apache.kafka=INFO"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - services-net
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - DYNAMIC_CONFIG_ENABLED=true
    depends_on:
      - kafka
    restart: unless-stopped

networks:
  services-net:
    driver: bridge